services:
  - type: web
    name: qrapp-backend
    env: docker
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: DB_PROVIDER
        value: mongo
      - key: MONGO_URI
        sync: false
      - key: MONGO_DB
        value: qr_app
      - key: MONGO_COLLECTION
        value: event_tickets


