SET NAMES utf8mb4;
USE qr_app;

INSERT INTO event_tickets (nombre, apellido, correo_electronico, tipo, pmr, hash, numero_local)
VALUES
    ('Cristina', 'Puig Solà', 'de3tac.test.entrades@yopmail.com', 4, TRUE, '0P1lS8buEaStQq8G4D3gV2kPCf657tZo', 2),
    ('Miquel', 'Díaz Cabot', 'de3tac.test.entrades@yopmail.com', 4, TRUE, '2BtRpLxqwBYMascnTmj2Crq9kQyJGrH2', 2),
    ('David', 'López Casas', 'de3tac.test.entrades@yopmail.com', 1, FALSE, '3ixKjlFKhmr97qVB7Y9RAzBJ3wVoc8YI', 1),
    ('Jordi', 'Martínez Soler', 'de3tac.test.entrades@yopmail.com', 4, TRUE, '6HmrvxnPxWYyHDTPZ3rxbeVrQAw1aGnY', 3),
    ('Marta', 'Pérez Ibáñez', 'de3tac.test.entrades@yopmail.com', 4, FALSE, '7Q5Mo7b85ecbn3FHPfpaK8xehsy4jDCV', 2),
    ('Núria', 'Jiménez Mas', 'de3tac.test.entrades@yopmail.com', 4, TRUE, '8fdvQH4p4glHhw3uRqKf1atruSCKGf6L', 4),
    ('Alba', 'Domínguez Cors', 'de3tac.test.entrades@yopmail.com', 4, FALSE, '953uWhFT2s2bIaCBeRaEclWgASKjbj9d', 3),
    ('David', 'López Casas', 'de3tac.test.entrades@yopmail.com', 4, FALSE, 'A7HUyUst089Bf8AIguyIcCABTB9cBUqq', 2),
    ('Oriol', 'Alonso Bosch', 'de3tac.test.entrades@yopmail.com', 4, FALSE, 'aFrrEJlGT8u3A5h8A9FWnNYS9VABQFUx', 2),
    ('Eva', 'Sánchez Roca', 'de3tac.test.entrades@yopmail.com', 4, FALSE, 'AohKPZSOd31Sx1OfFAjC2iRYo4uiaKpF', 1),
    ('Núria', 'Jiménez Mas', 'de3tac.test.entrades@yopmail.com', 4, TRUE, 'B9cXI1j9DiKpjmpGjo6X2myb0ghuqvMs', 2),
    ('David', 'López Casas', 'de3tac.test.entrades@yopmail.com', 4, FALSE, 'BB1UdlgKQK5dWPKLLF7QgCkApPA07EjV', 4),
    ('David', 'López Casas', 'de3tac.test.entrades@yopmail.com', 4, FALSE, 'bFLNIr9pJ2cLUq1wzoZG1dyKbQwYdf90', 5),
    ('Júlia', 'Muñoz Vergés', 'de3tac.test.entrades@yopmail.com', 4, FALSE, 'BMdcCSNUYjnW0RGe7TjrSKNXJDMF5HGU', 2),
    ('Berta', 'Hernández Font', 'de3tac.test.entrades@yopmail.com', 4, FALSE, 'Cdf9MjFlRPPNOBuIfWvzEPq6f6w2jCPE', 1),
    ('Núria', 'Jiménez Mas', 'de3tac.test.entrades@yopmail.com', 1, TRUE, 'cW4qfc2GzUSxADH9SykWs1iJVb1St8hK', 1),
    ('Anna', 'Ruiz Palau', 'de3tac.test.entrades@yopmail.com', 2, FALSE, 'DIFd3UuQkJTQgez4iVR7xThfJ8mpGZbv', 1),
    ('Sergi', 'Moreno Esteve', 'de3tac.test.entrades@yopmail.com', 4, FALSE, 'eK4aU45jQ0gqieqxmyVydShsCdK8QSes', 4),
    ('Júlia', 'Muñoz Vergés', 'de3tac.test.entrades@yopmail.com', 4, FALSE, 'Eo1edwAxyIYA0WZts6qJlLc1R4iEXAuZ', 1),
    ('Laia', 'Fernández Puig', 'de3tac.test.entrades@yopmail.com', 4, FALSE, 'ER4CRXTUCmHKGOBjFgEIYLEyIpiqmB7P', 3),
    ('Cristina', 'Puig Solà', 'de3tac.test.entrades@yopmail.com', 0, TRUE, 'FyxTyJRas1PWqkm3ISBdmGgj8ae1dS8j', 1),
    ('Oriol', 'Alonso Bosch', 'de3tac.test.entrades@yopmail.com', 4, FALSE, 'Gle81p3Av1EhR9yvwIAsxRLpXGguRNQ9', 4),
    ('Berta', 'Hernández Font', 'de3tac.test.entrades@yopmail.com', 4, FALSE, 'HDg6u5xL6qcWqeBMWg72q4cOzDxtTKt2', 4),
    ('Pau', 'Romero Ferrer', 'de3tac.test.entrades@yopmail.com', 1, FALSE, 'hfmGbumhiNW75w8tdITCOpBAWQZiDZEB', 1),
    ('Arnau', 'Torres Vidal', 'de3tac.test.entrades@yopmail.com', 3, FALSE, 'hgGRUa2hTAzWxogmdNmIYFS2QinRbVAp', 0),
    ('Alba', 'Domínguez Cors', 'de3tac.test.entrades@yopmail.com', 0, FALSE, 'IhUeEbJeBqS5fQb4wp2HCn2ZpayjQL2R', 1),
    ('Roger', 'Ramos Pla', 'de3tac.test.entrades@yopmail.com', 4, FALSE, 'jfPi3XOWSD5X8Hnl7uYAZ06Z3b2NaEXq', 2),
    ('Marc', 'García López', 'de3tac.test.entrades@yopmail.com', 4, FALSE, 'JTYw517hQz4ek7gpmNm3thegL4ggJLj8', 1),
    ('Pau', 'Romero Ferrer', 'de3tac.test.entrades@yopmail.com', 4, FALSE, 'kcPCpU36K1q6QiVhdLiZVJqI6X03hZZw', 3),
    ('Roger', 'Ramos Pla', 'de3tac.test.entrades@yopmail.com', 4, FALSE, 'KK11dZqKm7AX1arnbHEDmAynM57TfCnS', 3),
    ('Anna', 'Ruiz Palau', 'de3tac.test.entrades@yopmail.com', 4, FALSE, 'KtUl6TEG4XdN2LZaqFmusRR7PCD2rDYH', 2),
    ('Roger', 'Ramos Pla', 'de3tac.test.entrades@yopmail.com', 0, FALSE, 'LEKv0KDs5Fw69myJiuAYmek9CspyisoB', 1),
    ('Gerard', 'Navarro Sala', 'de3tac.test.entrades@yopmail.com', 0, TRUE, 'LoBJmJ7X5sfMPFnstlrqb5ASAoZL1g0R', 1),
    ('Eva', 'Sánchez Roca', 'de3tac.test.entrades@yopmail.com', 3, FALSE, 'lwo8FBLQqJhdpYeIBQbzdntooOryLAq7', 0),
    ('Pau', 'Romero Ferrer', 'de3tac.test.entrades@yopmail.com', 4, FALSE, 'MbRiRog4TDfjKoxrzi7kdS6CUozNTD53', 2),
    ('Alba', 'Domínguez Cors', 'de3tac.test.entrades@yopmail.com', 4, FALSE, 'MhkQtjmy34Trb2YVPHK4R5Ja1ZS1U943', 2),
    ('David', 'López Casas', 'de3tac.test.entrades@yopmail.com', 4, FALSE, 'mrvvTsYQopwKsYeKKZQyJGgJKmTcfZRb', 3),
    ('Gerard', 'Navarro Sala', 'de3tac.test.entrades@yopmail.com', 4, TRUE, 'MzlSukm4YbC7U9XkvXbKAnCC99fYqU8W', 3),
    ('Berta', 'Hernández Font', 'de3tac.test.entrades@yopmail.com', 4, FALSE, 'mZTTtcfTUVDr9MBZ0eJ3rJxVv5ZITPXC', 3),
    ('Jordi', 'Martínez Soler', 'de3tac.test.entrades@yopmail.com', 4, TRUE, 'NpXkiJLU2LY86LRqvqbC9B4wpK9eKX7n', 2),
    ('Oriol', 'Alonso Bosch', 'de3tac.test.entrades@yopmail.com', 4, FALSE, 'o0eUxnqxyrJfg0iCQq9fk89Sg7N2HVSq', 5),
    ('Laia', 'Fernández Puig', 'de3tac.test.entrades@yopmail.com', 3, FALSE, 'O0Xf6GdhkTnrlp6xWHaOF4BMGBihtC6V', 0),
    ('Carla', 'Gómez Llopis', 'de3tac.test.entrades@yopmail.com', 4, TRUE, 'OoozlnTuD1wDFFYvIxzfQ7VHQBKvZVxk', 3),
    ('Carla', 'Gómez Llopis', 'de3tac.test.entrades@yopmail.com', 2, TRUE, 'pKzPprhwcax2CXezDNe3mRL9pc3mqDqc', 1),
    ('Carla', 'Gómez Llopis', 'de3tac.test.entrades@yopmail.com', 4, TRUE, 'q1mgMQcVfeR9Zh01as5TTpWqHa0ji7VY', 2),
    ('Oriol', 'Alonso Bosch', 'de3tac.test.entrades@yopmail.com', 4, FALSE, 'qCF6x96zTs4jgQRUeO56TlLXMauv0JxA', 1),
    ('Marta', 'Pérez Ibáñez', 'de3tac.test.entrades@yopmail.com', 1, FALSE, 'rL0tIcXOZff1ThBYoiFI6u0PS3lCwBXM', 1),
    ('Gerard', 'Navarro Sala', 'de3tac.test.entrades@yopmail.com', 4, TRUE, 'SDxYJThEWhIX0riJ33f1u5oAaO6RAk5l', 2),
    ('Arnau', 'Torres Vidal', 'de3tac.test.entrades@yopmail.com', 4, FALSE, 'sf7Mbch9LpakvBYxKMWu5bWBIIOq6n7K', 2),
    ('Miquel', 'Díaz Cabot', 'de3tac.test.entrades@yopmail.com', 4, TRUE, 'SwHbXIiDtXTIKjR6hW1BCPBsfurIXxok', 1),
    ('Jordi', 'Martínez Soler', 'de3tac.test.entrades@yopmail.com', 3, TRUE, 'syce4VLwmNG6TKhJ5XU3ZH0LWvMjYbJE', 0),
    ('Carla', 'Gómez Llopis', 'de3tac.test.entrades@yopmail.com', 4, TRUE, 't2Fw3wHFa79idjzzUXimvxLB31Sblr07', 4),
    ('Núria', 'Jiménez Mas', 'de3tac.test.entrades@yopmail.com', 4, TRUE, 'tYWq9ZUAz7GngmKRGwCteRAcRaF56QwN', 3),
    ('Oriol', 'Alonso Bosch', 'de3tac.test.entrades@yopmail.com', 4, FALSE, 'ucgoEP2JXlfWrBnM1NK4cCUZtHuXek8s', 3),
    ('Jordi', 'Martínez Soler', 'de3tac.test.entrades@yopmail.com', 4, TRUE, 'Uj1wb64VS488c2JLpLJYNRqR5doEcT6S', 1),
    ('Marc', 'García López', 'de3tac.test.entrades@yopmail.com', 3, FALSE, 'UTKWCL5dLCzqATQ4yocmj3KjEtjFl7x4', 0),
    ('Roger', 'Ramos Pla', 'de3tac.test.entrades@yopmail.com', 4, FALSE, 'UU0gSChU7zk2XMZAGfjZ1UcNXX9sc8uj', 5),
    ('Alba', 'Domínguez Cors', 'de3tac.test.entrades@yopmail.com', 4, FALSE, 'VGHBrmVsxIUPcxED4QZjeffZteYZPtee', 4),
    ('Miquel', 'Díaz Cabot', 'de3tac.test.entrades@yopmail.com', 4, TRUE, 'VPSqwUtlSBl6pbRQeCUAxBjdkxNvv1ul', 3),
    ('Laia', 'Fernández Puig', 'de3tac.test.entrades@yopmail.com', 4, FALSE, 'wJj06PNqVp7EUxu8LHMlAUMGy1uCBPFl', 1),
    ('Marc', 'García López', 'de3tac.test.entrades@yopmail.com', 4, FALSE, 'wthrFkgiJAUA63FlvDiP4AsV248JBVLK', 2),
    ('Sergi', 'Moreno Esteve', 'de3tac.test.entrades@yopmail.com', 4, FALSE, 'WyhZzj43R2cKRpukgNmKijRkVECsx5KV', 2),
    ('Arnau', 'Torres Vidal', 'de3tac.test.entrades@yopmail.com', 4, FALSE, 'XcMdJWRGnYgCAjs1nALW5N1G9cyjZi6w', 1),
    ('Berta', 'Hernández Font', 'de3tac.test.entrades@yopmail.com', 4, FALSE, 'xXZBfwzi5TMnH643aDuWmcodmrwstRVT', 2),
    ('Roger', 'Ramos Pla', 'de3tac.test.entrades@yopmail.com', 4, FALSE, 'YKvJL6d4jrO5y7Wmkx4Blx840Ihl9Vej', 4),
    ('Sergi', 'Moreno Esteve', 'de3tac.test.entrades@yopmail.com', 2, FALSE, 'YPywSACPqFZad6IdEDy8N4IbJkp0YE96', 1),
    ('Laia', 'Fernández Puig', 'de3tac.test.entrades@yopmail.com', 4, FALSE, 'Yqh78pRr24K2yZTdj4CRRnw5T5yv9egQ', 2),
    ('Sergi', 'Moreno Esteve', 'de3tac.test.entrades@yopmail.com', 4, FALSE, 'YxJNfj7Jww73bdkScydPmJ2YIUKGqrtt', 5),
    ('Jordi', 'Martínez Soler', 'de3tac.test.entrades@yopmail.com', 4, TRUE, 'zHvoHOhsvEMIQPPrfZStgy72dxfg33Y8', 4),
    ('Sergi', 'Moreno Esteve', 'de3tac.test.entrades@yopmail.com', 4, FALSE, 'ZOG9AWlxmcZyabaXNMhJnF1RMTnrfHj2', 3)
ON DUPLICATE KEY UPDATE
    nombre = VALUES(nombre),
    apellido = VALUES(apellido),
    correo_electronico = VALUES(correo_electronico),
    tipo = VALUES(tipo),
    pmr = VALUES(pmr),
    numero_local = VALUES(numero_local);
